# Generated by Django 3.2.4 on 2021-07-10 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.CharField(max_length=50, null=True)),
                ('disciption', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachName', models.CharField(max_length=50, null=True)),
                ('disciption', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('pricePerHour', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('title', models.CharField(max_length=50, null=True)),
                ('disciption', models.TextField(max_length=500, null=True)),
                ('catgorie', models.CharField(choices=[('LOL', 'league of legendes'), ('OR', 'origin'), ('ST', 'steam'), ('OT', 'other')], default='', max_length=3)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.accounts'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.coach'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.game'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.accounts'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.coach'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='Game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaco.game'),
        ),
    ]
