# Generated by Django 3.2.4 on 2021-07-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0004_auto_20210730_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boostreview',
            name='Boost',
        ),
    ]
