# Generated by Django 3.2.4 on 2021-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0005_remove_boostreview_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institue', models.CharField(blank=True, max_length=60)),
                ('anneScolere', models.CharField(blank=True, max_length=9)),
                ('cin', models.IntegerField(blank=True, max_length=8)),
                ('nomEtudian', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='boost',
            name='User',
        ),
        migrations.RemoveField(
            model_name='boostreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='User',
        ),
        migrations.RemoveField(
            model_name='coachreview',
            name='Coach',
        ),
        migrations.RemoveField(
            model_name='coachreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='User',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Accounts',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Boost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Coach',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Game',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddres',
            name='order',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Boost',
        ),
        migrations.DeleteModel(
            name='BoostReview',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='CoachReview',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='orderItem',
        ),
        migrations.DeleteModel(
            name='shippingAddres',
        ),
    ]
