# Generated by Django 3.2.4 on 2021-08-14 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0007_pfe_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='uniqueID',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
