# Generated by Django 3.2.4 on 2021-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0009_alter_pfe_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
