# Generated by Django 3.2.4 on 2021-08-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0011_alter_pfe_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='createdAt',
        ),
    ]
