# Generated by Django 3.2.4 on 2021-09-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0012_remove_pfe_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='cin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='uniqueID',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
