# Generated by Django 3.2.4 on 2021-09-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0013_auto_20210903_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='cin',
            field=models.IntegerField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='pfe',
            name='uniqueID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
