# Generated by Django 3.2.4 on 2021-09-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0015_auto_20210903_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='file',
        ),
        migrations.RemoveField(
            model_name='pfe',
            name='notes',
        ),
    ]
