# Generated by Django 3.2.4 on 2021-09-03 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0016_auto_20210903_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
