# Generated by Django 3.2.4 on 2021-09-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaco', '0017_pfe_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='file',
        ),
    ]
